
name = "limitless-web-dynamic"
compatibility_date = "2024-11-06"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "limitless_web_db"
database_id = "local-dev-only" # For local dev; bind the real DB in Cloudflare Pages -> Settings -> Functions -> D1

[vars]
ADMIN_USER = "123"
ADMIN_PASS = "123"
ADMIN_SECRET = "change-me"
